# Generated by Django 6.0.3 on 2026-04-09 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExperimentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "run_kind",
                    models.CharField(
                        choices=[
                            ("cascade", "Cascade Simulation"),
                            ("dataset", "Dataset Generation"),
                            ("training", "Model Training"),
                            ("optimization", "Repair Optimization"),
                            ("evaluation", "Evaluation"),
                            ("dashboard", "Dashboard Snapshot"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("run_identifier", models.CharField(max_length=80, unique=True)),
                ("source_commit", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("input_summary", models.JSONField(blank=True, default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("rainfall_year", models.PositiveIntegerField(default=2020)),
                ("severity_scale", models.FloatField(default=1.0)),
                ("capacity_factor", models.FloatField(default=1.25)),
                ("overload_factor", models.FloatField(default=1.5)),
                ("max_steps", models.PositiveIntegerField(default=20)),
                ("random_seed", models.PositiveIntegerField(blank=True, null=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_baseline", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "scenario configuration",
                "verbose_name_plural": "scenario configurations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RunArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=120)),
                (
                    "artifact_kind",
                    models.CharField(
                        choices=[
                            ("graph", "Graph"),
                            ("dataset", "Dataset"),
                            ("model", "Model"),
                            ("metrics", "Metrics"),
                            ("geojson", "GeoJSON"),
                            ("plot", "Plot"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "relative_path",
                    models.CharField(
                        help_text="Path relative to the repository root.",
                        max_length=255,
                    ),
                ),
                ("file_format", models.CharField(blank=True, max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="dashboard.experimentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "unique_together": {("run", "label", "relative_path")},
            },
        ),
        migrations.CreateModel(
            name="ModelResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(max_length=120)),
                ("model_family", models.CharField(max_length=80)),
                ("dataset_name", models.CharField(max_length=120)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("node_failure", "Node Failure Prediction"),
                            ("temporal_failure", "Temporal Failure Prediction"),
                            ("resilience", "Resilience Estimation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("train_rows", models.PositiveIntegerField(default=0)),
                ("test_rows", models.PositiveIntegerField(default=0)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("hyperparameters", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_results",
                        to="dashboard.experimentrun",
                    ),
                ),
                (
                    "model_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trained_models",
                        to="dashboard.runartifact",
                    ),
                ),
            ],
            options={
                "ordering": ["model_family", "model_name"],
            },
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="dashboard.scenarioconfig",
            ),
        ),
        migrations.CreateModel(
            name="OptimizationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("strategy_name", models.CharField(max_length=120)),
                ("budget_k", models.PositiveIntegerField()),
                ("mean_failed", models.FloatField()),
                ("std_failed", models.FloatField(default=0.0)),
                ("resilience_score", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_results",
                        to="dashboard.experimentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["strategy_name", "budget_k"],
                "unique_together": {("run", "strategy_name", "budget_k")},
            },
        ),
    ]
